### PR TITLE
Added custom attributes option to get_device_info in api.py in order to retrieve custom attributes from traccar

### PR DESCRIPTION
**Pull request by lapy**
Thanks for your fantastic traccar python client.

I need to get some custom attributes from traccar and I modified the API class to include that.

I hope you don't mind to merge this with your repo!

Thank you,
Vince

### CODE REVIEW

**Comment by ludeeus** [comment]
Are the attributes you need custom created by you in traccar, of missing default attributes?

BTW: _Don't think about the travis error in this case_

**Comment by lapy** [comment]
In my specific case I need to monitor the attribute "alarm" which appears in traccar only when a device sends an alarm message (motion detected or sos button). I didn't create the attribute so I guess it is a default attribute. I am using this pytraccar client with the Home Assistant component, which I had to modify as well to include this new attribute.

**Comment by ludeeus** [comment]
Okey then :)

I'll merge this now and prepare a release later today.

**Comment by lapy** [comment]
Great! thank you :)
I hope you don't mind if I propose my changes on the HASS traccar component as well!

**Comment by ludeeus** [comment]
Go for it, I have limited time to do it myself :P

**Pull request merged**
